name: Deploy to Vercel

on:
  push:
    branches:
      - master

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clean and Install Dependencies
        run: npm install

      - name: Set Environment Variables
        run: |
          echo "REACT_APP_ACCESS_KEY=${{ secrets.CLIENT_ID }}" >> .env.local
          echo "REACT_APP_BASE_URL=${{ secrets.BASE_URL }}" >> .env.local

      - name: Build and Deploy to Vercel
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }} --env .env
