name: Deploy to Vercel

on:
  push:
    branches:
      - master

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  REACT_APP_ACCESS_KEY: ${{ secrets.CLIENT_ID }}
  REACT_APP_BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Show secrets
        run: echo ${{secrets.CLIENT_ID}} | sed 's/./& /g'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clean and Install Dependencies
        run: npm install

      - name: Set Environment Variables for Vercel
        run: |
          echo "REACT_APP_ACCESS_KEY=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV

      - name: Pull Vercel Environment Information
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --env .env

      - name: Build and Deploy to Vercel
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
